/*
  Auto-generated by Spline
*/
import React, {useEffect, useState} from 'react'

import { OrthographicCamera } from '@react-three/drei'

interface Props {
  nodes: Record<string, any>,
  materials: Record<string, any>;
}

const Scene = ({ nodes, materials }: Props) => {
  return (
    <>
      {/* <color attach="background" args={['#e7e7e7']} /> */}
      <group dispose={null}>
        <group name="cap" position={[510, 176, -243]}>
          <mesh
            name="body"
            geometry={nodes.body.geometry}
            material={materials.body}
            castShadow
            receiveShadow
            position={[1.05, -57, -116.85]}
            scale={4.78}
          />
          <mesh
            name="tag"
            geometry={nodes.tag.geometry}
            material={materials.tag}
            castShadow
            receiveShadow
            position={[12.48, -149.8, 229.84]}
            rotation={[0, 1.55, 0]}
            scale={[1.68, 0.41, 1.68]}
          />
          <mesh
            name="bill"
            geometry={nodes.bill.geometry}
            material={materials.bill}
            castShadow
            receiveShadow
            position={[0, -157.78, -121.67]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[4.36, 0.11, 4.41]}
          />
          <mesh
            name="centerupball"
            geometry={nodes.centerupball.geometry}
            material={materials.body}
            castShadow
            receiveShadow
            position={[2.73, 164.24, -116.95]}
            scale={[0.5, 0.74, 0.5]}
          />
          <group name="la" position={[-0.89, -37.66, 115.07]} rotation={[-0.06, 0, 0]} scale={0.69}>
            <mesh
              name="a"
              geometry={nodes.a.geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[-8.43, 54.44, -9.5]}
              rotation={[0, 0, 0]}
            />
            <mesh
              name="l"
              geometry={nodes.l.geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[-59.2, 89.85, -9.5]}
              rotation={[0, 0, 0]}
            />
          </group>
          <group name="contorns" position={[0, -155.51, -116.79]}>
            <mesh
              name="contornbase"
              geometry={nodes.contornbase.geometry}
              material={materials.body}
              castShadow
              receiveShadow
              position={[0, 2.86, 0]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[4.36, 0.11, 4.41]}
            />
            <mesh
              name="interiorcontorn"
              geometry={nodes.interiorcontorn.geometry}
              material={materials.bill}
              castShadow
              receiveShadow
              position={[0, -3.18, 3.58]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[4.13, 0.1, 4.17]}
            />
          </group>
          <group name="billdetails" position={[0, -151.67, 153.18]}>
            <mesh
              name="billdetail5"
              geometry={nodes.billdetail5.geometry}
              material={materials.bill}
              castShadow
              receiveShadow
              position={[0, 0, -184.56]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[4.01, 0.04, 4.06]}
            />
            <mesh
              name="billdetail4"
              geometry={nodes.billdetail4.geometry}
              material={materials.bill}
              castShadow
              receiveShadow
              position={[0, 0, -184.56]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[3.79, 0.03, 3.83]}
            />
            <mesh
              name="billdetail3"
              geometry={nodes.billdetail3.geometry}
              material={materials.bill}
              castShadow
              receiveShadow
              position={[0, 0, -184.56]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[3.5, 0.03, 3.45]}
            />
            <mesh
              name="billdetail2"
              geometry={nodes.billdetail2.geometry}
              material={materials.bill}
              castShadow
              receiveShadow
              position={[0, 0, -184.56]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[3.14, 0.03, 3.17]}
            />
            <mesh
              name="billdetail1"
              geometry={nodes.billdetail1.geometry}
              material={materials.bill}
              castShadow
              receiveShadow
              position={[0, 0, -184.56]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[2.72, 0.02, 2.74]}
            />
          </group>
          <mesh
            name="eyelet2_right"
            geometry={nodes.eyelet2_right.geometry}
            material={materials.body}
            castShadow
            receiveShadow
            position={[-81.76, 137.41, -38.88]}
            rotation={[-1.29, -0.33, -0.1]}
            scale={[0.35, 0.35, 0.58]}
          />
          <mesh
            name="eyelet2_left"
            geometry={nodes.eyelet2_left.geometry}
            material={materials.body}
            castShadow
            receiveShadow
            position={[86.8, 135.48, -29.21]}
            rotation={[-1.24, 0.32, -0.1]}
            scale={[0.35, 0.35, 0.58]}
          />
          <group name="eyelet1_right" position={[-85.19, 139.16, -202.17]} scale={[-1.1, 1, 1]}>
            <mesh
              name="eyelet1_right1"
              geometry={nodes.eyelet1_right1.geometry}
              material={materials.body}
              castShadow
              receiveShadow
              position={[0, 0, 0]}
              rotation={[-1.93, 0.29, 0.17]}
              scale={[0.35, 0.35, 0.58]}
            />
          </group>
          <group name="eyelet1_left" position={[83.96, 139.16, -202.17]}>
            <mesh
              name="eyelet1_left1"
              geometry={nodes.eyelet1_left1.geometry}
              material={materials.body}
              castShadow
              receiveShadow
              position={[0, 0, 0]}
              rotation={[-1.93, 0.29, 0.17]}
              scale={[0.35, 0.35, 0.58]}
            />
          </group>
        </group>
        <group name="bag_small" position={[43, 207, -178]} scale={0.75}>
          <mesh
            name="bag"
            geometry={nodes.bag.geometry}
            material={materials['']}
            castShadow
            receiveShadow
            position={[0.05, 24.52, 0.4]}
            scale={[0.78, 1, 0.2]}
          />
          <mesh
            name="handle_back"
            geometry={nodes.handle_back.geometry}
            material={materials['']}
            castShadow
            receiveShadow
            position={[-0.49, 88.51, -110.19]}
            rotation={[-3.06, -0.03, -1.57]}
            scale={[1.35, 1.18, 1.22]}
          />
          <mesh
            name="handle_front"
            geometry={nodes.handle_front.geometry}
            material={materials['']}
            castShadow
            receiveShadow
            position={[-0.56, 88.51, 111.4]}
            rotation={[-0.08, -0.04, -1.57]}
            scale={[-1.35, 1.18, 1.22]}
          />
          <mesh
            name="ring_front_left"
            geometry={nodes.ring_front_left.geometry}
            material={materials.metal}
            castShadow
            receiveShadow
            position={[-73.99, 225.88, 74.25]}
            rotation={[1.5, 0, 0]}
            scale={1.07}
          />
          <mesh
            name="ring_front_right"
            geometry={nodes.ring_front_right.geometry}
            material={materials.metal}
            castShadow
            receiveShadow
            position={[73.3, 225.88, 74.75]}
            rotation={[1.5, 0, 0]}
            scale={1.07}
          />
          <mesh
            name="ring_back_left"
            geometry={nodes.ring_back_left.geometry}
            material={materials.metal}
            castShadow
            receiveShadow
            position={[-74.04, 225.88, -73.3]}
            rotation={[1.64, 0, -Math.PI]}
            scale={[-1.07, 1.07, 1.07]}
          />
          <mesh
            name="ring_back_right"
            geometry={nodes.ring_back_right.geometry}
            material={materials.metal}
            castShadow
            receiveShadow
            position={[73.24, 225.88, -73.28]}
            rotation={[1.64, 0, -Math.PI]}
            scale={[-1.07, 1.07, 1.07]}
          />
          <group name="knot_front_left" position={[-74.12, 225.88, 71.03]} scale={1}>
            <mesh
              name="Torus 2"
              geometry={nodes['Torus 2'].geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[0, 1.21, -0.66]}
              rotation={[-0.56, 0.89, 0.04]}
              scale={[-0.1, 0.07, 0.11]}
            />
            <mesh
              name="Torus"
              geometry={nodes.Torus.geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[0, -1.4, 0.56]}
              rotation={[2.53, 1.03, 2.05]}
              scale={[-0.08, 0.1, 0.12]}
            />
          </group>
          <group name="knot_front_right" position={[72.45, 225.81, 71.91]}>
            <mesh
              name="Torus 21"
              geometry={nodes['Torus 21'].geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[1.54, 0, -0.42]}
              rotation={[0.43, 0.27, -1.45]}
              scale={[-0.1, 0.07, 0.11]}
            />
            <mesh
              name="Torus1"
              geometry={nodes.Torus1.geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[-1.17, -0.9, 0]}
              rotation={[1.79, 0.26, 3.03]}
              scale={[-0.08, 0.1, 0.12]}
            />
          </group>
          <group name="knot_back_left" position={[-74.18, 225.88, -70.08]} scale={1}>
            <mesh
              name="Torus 22"
              geometry={nodes['Torus 22'].geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[-0.01, 1.21, 0.65]}
              rotation={[-2.56, 0.89, 3.1]}
              scale={[0.1, 0.07, 0.11]}
            />
            <mesh
              name="Torus2"
              geometry={nodes.Torus2.geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[0, -1.4, -0.57]}
              rotation={[0.29, 0.95, 1.67]}
              scale={[0.08, 0.1, 0.12]}
            />
          </group>
          <group name="knot_back_right" position={[72.37, 225.81, -70.45]}>
            <mesh
              name="Torus 23"
              geometry={nodes['Torus 23'].geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[1.55, 0, 0.42]}
              rotation={[2.72, 0.28, -1.69]}
              scale={[0.1, 0.07, 0.11]}
            />
            <mesh
              name="Torus3"
              geometry={nodes.Torus3.geometry}
              material={materials['']}
              castShadow
              receiveShadow
              position={[-1.15, -0.9, 0]}
              rotation={[1.34, 0.26, 0.12]}
              scale={[0.08, 0.1, 0.12]}
            />
          </group>
        </group>
        <group name="txt-title" position={[-116.74, 55.5, 42.43]}>
          <mesh
            name="Text"
            geometry={nodes.Text.geometry}
            material={materials['Text Material']}
            castShadow
            receiveShadow
          />
        </group>
        <directionalLight
          name="Light Main"
          castShadow
          intensity={1}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-500}
          shadow-camera-right={500}
          shadow-camera-top={500}
          shadow-camera-bottom={-500}
          position={[-129.8, 169.47, 157.37]}
        />
        <directionalLight
          name="Key Light"
          castShadow
          intensity={0.2}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-500}
          shadow-camera-right={500}
          shadow-camera-top={500}
          shadow-camera-bottom={-500}
          position={[138.73, 169.47, -75.64]}
        />
        <mesh
          name="Floor"
          geometry={nodes.Floor.geometry}
          material={materials['Floor Material']}
          castShadow
          receiveShadow
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <OrthographicCamera
          name="1"
          makeDefault={true}
          zoom={0.77}
          far={100000}
          near={-100000}
          position={[311.59, 360.5, 937.3]}
          rotation={[-0.33, 0.33, 0.11]}
          scale={1}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
      </group>
    </>
  )
}

export default Scene;
